// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnlaAPl2UlKpEXDWNVy7e9E_6OmiLeMxg',
    appId: '1:354117576678:web:e8ef421a394cb63f7c5827',
    messagingSenderId: '354117576678',
    projectId: 'todoflutter-e0797',
    authDomain: 'todoflutter-e0797.firebaseapp.com',
    storageBucket: 'todoflutter-e0797.firebasestorage.app',
    measurementId: 'G-XMG695ZPSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKtO04aGn4_ThTAXGRmaBHN8HKmVRLIhg',
    appId: '1:354117576678:android:36017c72c347b9077c5827',
    messagingSenderId: '354117576678',
    projectId: 'todoflutter-e0797',
    storageBucket: 'todoflutter-e0797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6Z4lXR_kNd9AxifWeT9khKcF7DbJCOY',
    appId: '1:354117576678:ios:6888eb8d0123b1727c5827',
    messagingSenderId: '354117576678',
    projectId: 'todoflutter-e0797',
    storageBucket: 'todoflutter-e0797.firebasestorage.app',
    iosBundleId: 'com.todoapp.todo.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_APP_ID:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.todoapp.todoFlutter',
  );
}
